[package]
name = "mgv-ui"
description = "Moonglow Viewer's user interface (egui)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui_commonmark.workspace = true
egui_dock.workspace = true
glam.workspace = true
mg-core.workspace = true
mg-image.workspace = true
mg-mdl.workspace = true
mg-render.workspace = true
mg-resman.workspace = true
mg-set.workspace = true
mgv-library.workspace = true
mgv-mdl.workspace = true
mgv-stage.workspace = true
serde.workspace = true
wgpu.workspace = true

[dev-dependencies]
mg-render.workspace = true
egui_kittest = { workspace = true, features = ["wgpu", "snapshot"] }
mg-testkit.workspace = true

[lints]
workspace = true
