# Windows builds carry the C runtime inside the executables, so they run
# without the Visual C++ Redistributable installed.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
